[package]
name = "bed-utils"
version = "0.1.0"
edition = "2021"
authors = ["Kai Zhang <kai@kzhang.org>"]

[dependencies]
noodles = { version = "0.15.0", features = ["bam"] }
bio = "0.39.0"
itertools = "0.8"