name: 'Build and push Docker images'
description: 'Builds and pushes Docker images to Dockerhub'

inputs:
  snapatac2-version:
    description: 'SnapATAC2 version to be installed'
    required: true
    type: string
  python-version:
    required: false
    default: "3.11"
  flavor:
    required: false
    default: "default"
  dockerhub_username:
    required: true
  dockerhub_token:
    required: true

runs:
  using: "composite"
  steps:
    # Should result in something like: `IMAGE_TAG=2.5.1-default-py3.11` or `IMAGE_TAG=2.5.1-recommend-interactive-py3.11`
    - name: Create Docker image tag
      run: echo "IMAGE_TAG=${{ inputs.snapatac2-version }}-${{ inputs.flavor }}-py${{ inputs.python-version }}" >> $GITHUB_ENV
      shell: bash

    # https://github.com/nschloe/action-cached-lfs-checkout
    # TODO: This action uses an older (slower) version of actions/checkout@v3
    #       try to update this as soon as maintainer releases new version
    - name: Checkout repository
      uses: nschloe/action-cached-lfs-checkout@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # TODO: Has SnapATAC2 been tested for arm64? If it has and it works then uncomment the following
    #       section and also add `linux/arm64` to `platforms` in subsequent steps:
    # # https://github.com/docker/setup-qemu-action
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3
    # https://github.com/docker/build-push-action
    # Uses github actions cache: https://docs.docker.com/build/cache/backends/gha/
    - name: Build Dockerfile
      uses: docker/build-push-action@v5
      with:
        context: docker/${{ inputs.flavor }}
        platforms: linux/amd64
        build-args: |
          BASE_PYTHON_IMAGE=python:${{ inputs.python-version }}-slim
          SNAP_ATAC_VERSION=${{ inputs.snapatac2-version }}
        load: true
        tags: snapatac2:TEST-${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Mount the Github Workspace (repository root) into our test container
    # Then install test required packages and run SnapATAC2 Python tests
    - name: Test Docker Image
      shell: bash
      run: |
        docker run --rm -t \
          --entrypoint /bin/bash \
          --volume "${{ github.workspace }}":"/github/workspace" \
          snapatac2:TEST-${{ env.IMAGE_TAG }} \
          -c "python3 -m pip install pytest hypothesis && pytest /github/workspace/snapatac2-python/tests"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    # Uses cached result from first build
    - name: Push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: docker/${{ inputs.flavor }}
        platforms: linux/amd64
        build-args: |
          BASE_PYTHON_IMAGE=python:${{ inputs.python-version }}-slim
          SNAP_ATAC_VERSION=${{ inputs.snapatac2-version }}
        push: true
        tags: snapatac2:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max