name: Continuous integration

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11, windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install dependency (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y libhdf5-serial-dev

    - name: Install dependency (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install hdf5

    - name: Install dependency (Windows)
      if: runner.os == 'Windows'
      run: |
        pip install --user requests
        python ci/get_hdf5_win.py

    - name: Install dependency (all)
      run: |
        pip install --upgrade --user pip typing_extensions

    - name: Build and test package
      run: |
        cd snapatac2-core && cargo test --all --no-fail-fast
        cd ../snapatac2-python && pip install --user .
        python tests/test.py