name: Documentation

env:
  PYTHON_LIB: snapatac2-python

on: [push, pull_request]

jobs:
  build_doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install sphinx dependency
      run: |
        sudo apt-get install -y pandoc
        pip install --user Pygments==2.6.1 sphinx==4.4.0 pandoc nbsphinx \
          sphinx-autodoc-typehints \
          sphinxcontrib-versioning \
          sphinx_rtd_theme

    - name: Install package dependency
      run: |
        sudo pip install --upgrade setuptools
        pip install --user setuptools-rust
        cd $GITHUB_WORKSPACE/$PYTHON_LIB && python setup.py egg_info
        pip install --user -r *.egg-info/requires.txt

    - name: Build doc
      run: cd ${GITHUB_WORKSPACE}/docs && make html

    - name: Upload doc
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: ./docs/_build/html

  upload_gh-page:
    #if: startsWith(github.ref, 'refs/tags/v')
    name: Publish
    runs-on: ubuntu-latest
    needs: [build_doc]
    steps:
    - name: Download
      uses: actions/download-artifact@v2

    - name: Upload doc
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation
        publish_branch: gh-pages
        force_orphan: true